"""Photo processing core tests (Slice 10, FR-2).

EXIF fixtures are SYNTHETIC — generated by Pillow in-test (F-9: no real
photos, no real GPS). Stripping is proven by marker-level scan of the output
bytes (no APP1/Exif segment), which covers GPS a fortiori.
"""

from io import BytesIO

import pytest
from PIL import Image

from app.photo import MAX_PHOTO_BYTES, process_photo


def jpeg_with_exif(width: int, height: int, orientation: int | None = None) -> bytes:
    img = Image.new("RGB", (width, height), (120, 30, 30))
    exif = Image.Exif()
    exif[0x010F] = "TestCam"  # Make — device metadata (RODO target)
    exif[0x0110] = "TestCam Model X"  # Model
    if orientation is not None:
        exif[0x0112] = orientation
    out = BytesIO()
    img.save(out, format="JPEG", exif=exif.tobytes())
    return out.getvalue()


def png_with_alpha(width: int, height: int) -> bytes:
    img = Image.new("RGBA", (width, height), (0, 0, 0, 0))  # fully transparent
    out = BytesIO()
    img.save(out, format="PNG")
    return out.getvalue()


def has_app1_exif(data: bytes) -> bool:
    """Marker-level scan: any APP1 segment starting with b'Exif' before SOS."""
    i = 2
    while i + 4 < len(data) and data[i] == 0xFF:
        marker, seglen = data[i + 1], int.from_bytes(data[i + 2 : i + 4], "big")
        if marker == 0xDA:
            break
        if marker == 0xE1 and data[i + 4 : i + 8] == b"Exif":
            return True
        i += 2 + seglen
    return False


def test_output_is_jpeg_without_exif():
    src = jpeg_with_exif(300, 200)
    assert has_app1_exif(src)  # sanity: the fixture really carries EXIF
    out, w, h = process_photo(src)
    assert out[:3] == b"\xff\xd8\xff"
    assert not has_app1_exif(out)
    assert Image.open(BytesIO(out)).getexif() == {}  # belt and suspenders
    assert (w, h) == (300, 200)


def test_downscales_long_side_to_1200():
    out, w, h = process_photo(jpeg_with_exif(2400, 1600))
    assert (w, h) == (1200, 800)
    assert Image.open(BytesIO(out)).size == (1200, 800)


def test_never_upscales():
    _, w, h = process_photo(jpeg_with_exif(800, 600))
    assert (w, h) == (800, 600)


def test_orientation_transposed_before_strip():
    # Orientation=6 (90° CW): a 400x300 sensor image must come out 300x400.
    _, w, h = process_photo(jpeg_with_exif(400, 300, orientation=6))
    assert (w, h) == (300, 400)


def test_png_alpha_flattened_to_white_jpeg():
    out, w, h = process_photo(png_with_alpha(50, 40))
    img = Image.open(BytesIO(out))
    assert img.format == "JPEG"
    assert img.getpixel((25, 20)) == (255, 255, 255)


def test_garbage_raises():
    with pytest.raises(Exception):
        process_photo(b"not an image at all")


def test_max_photo_bytes_constant():
    assert MAX_PHOTO_BYTES == 10 * 1024 * 1024
