"""/coop-sheet and /geocode-batch (T-13, S2a). Offline: the fixture is the SYNTHETIC
register generated by apps/web/tests/fixtures/coop-registry-synthetic.mts; the
expected JSON next to it is the contract the web-side domain tests parse."""

import hashlib
import hmac
import json
import time
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from app import coop_xls, main

client = TestClient(main.app)
SECRET = "test-secret"
FIXTURES = Path(__file__).resolve().parents[2] / "web" / "tests" / "fixtures"
XLSX = FIXTURES / "coop-registry-synthetic.xlsx"
EXPECTED = json.loads((FIXTURES / "coop-registry-synthetic.sheets.json").read_text())


def mint(exp_offset: int = 300) -> str:
    exp = int(time.time()) + exp_offset
    nonce = "cafe0123"
    sig = hmac.new(SECRET.encode(), f"{exp}.{nonce}".encode(), hashlib.sha256).hexdigest()
    return f"{exp}.{nonce}.{sig}"


@pytest.fixture(autouse=True)
def secret_env(monkeypatch):
    monkeypatch.setenv("WORKER_SHARED_SECRET", SECRET)


def post(token: str, content: bytes | None = None, name="rejestr.xlsx", mime=coop_xls.XLSX_MIME):
    data = XLSX.read_bytes() if content is None else content
    return client.post("/coop-sheet", data={"token": token}, files={"file": (name, data, mime)})


def test_synthetic_register_matches_the_contract_json():
    r = post(mint())
    assert r.status_code == 200
    assert r.json() == EXPECTED


def test_two_sheets_dates_iso_empty_cells_padded_and_decimal_comma_kept_as_text():
    sheets = post(mint()).json()["sheets"]
    assert [s["name"] for s in sheets] == ["Rejestr 2025", "Bez nagłówka", "Bez nr mieszkania"]
    first = sheets[0]
    assert all(len(r) == first["cols"] for r in first["rows"])
    assert first["rows"][4][6] == "2025-01-14"  # a real date cell → ISO
    assert first["rows"][7][4:7] == ["52,10", "520 000", "02.01.2023r."]  # text stays text
    assert first["rows"][2] == [""] * first["cols"]  # blank row, padded
    assert first["rows"][4][4] == "45.5" and first["rows"][4][5] == "455000"
    assert sheets[1]["rows"][0][4] == "ul. Bukowa 12/5"


def test_no_header_sheet_starts_at_row_zero():
    second = post(mint()).json()["sheets"][1]
    assert second["rows"][0][0] == "A 1234/2025"


def test_rejects_bad_token():
    assert post("nope").status_code == 401
    assert post(mint(exp_offset=-10)).status_code == 401


def test_rejects_non_xlsx_by_mime_and_name():
    r = post(mint(), content=b"%PDF-1.4", name="skan.pdf", mime="application/pdf")
    assert r.status_code == 415


def test_rejects_garbage_with_xlsx_name():
    r = post(mint(), content=b"not a zip at all", name="x.xlsx")
    assert r.status_code == 422


def test_rejects_oversize(monkeypatch):
    monkeypatch.setattr(main, "coop_max_bytes", lambda: 10)
    assert post(mint()).status_code == 413


def test_rejects_a_sheet_with_too_many_rows(monkeypatch):
    monkeypatch.setattr(coop_xls, "MAX_ROWS_PER_SHEET", 5)
    r = post(mint())
    assert r.status_code == 413
    assert "wierszy" in r.json()["detail"]


def test_cell_text_conversions():
    from datetime import date, datetime

    assert coop_xls.cell_text(None) == ""
    assert coop_xls.cell_text(datetime(2025, 1, 14)) == "2025-01-14"
    assert coop_xls.cell_text(datetime(2025, 1, 14, 9, 30)) == "2025-01-14T09:30:00"
    assert coop_xls.cell_text(date(2025, 1, 14)) == "2025-01-14"
    assert coop_xls.cell_text(455000.0) == "455000"
    assert coop_xls.cell_text(45.5) == "45.5"
    assert coop_xls.cell_text(True) == "TRUE"


def test_geocode_batch_returns_hit_or_none_per_address_sequentially(monkeypatch):
    calls: list[str] = []

    def fake_resolve(address, point):
        calls.append(address)
        if "brak" in address:
            raise main.subject.AddressNotFound(address)
        return 360000.0, 504000.0, "uug"

    monkeypatch.setattr(main, "resolve_point", fake_resolve)
    r = client.post(
        "/geocode-batch",
        json={"token": mint(), "addresses": ["Poznań, Zmyślona 4", "Poznań, brak 1"]},
    )
    assert r.status_code == 200
    body = r.json()
    assert body["results"] == [{"x": 360000.0, "y": 504000.0, "source": "uug"}, None]
    assert (body["attempted"], body["resolved"], body["failed"]) == (2, 1, 1)
    assert calls == ["Poznań, Zmyślona 4", "Poznań, brak 1"]


def test_geocode_batch_pauses_after_a_nominatim_miss_too(monkeypatch):
    sleeps: list[float] = []
    monkeypatch.setattr(main.time, "sleep", lambda s: sleeps.append(s))

    def fake_resolve(address, point):
        if address == "uug":
            return 1.0, 2.0, "uug"
        if address == "nominatim":
            return 1.0, 2.0, "nominatim"
        raise main.subject.AddressNotFound(address)  # both geocoders consulted, none knew

    monkeypatch.setattr(main, "resolve_point", fake_resolve)
    r = client.post(
        "/geocode-batch", json={"token": mint(), "addresses": ["uug", "nominatim", "miss"]}
    )
    assert r.status_code == 200
    assert sleeps == [main.NOMINATIM_PAUSE_S, main.NOMINATIM_PAUSE_S]  # not after the UUG hit


def test_geocode_batch_requires_token_and_caps_size():
    assert client.post("/geocode-batch", json={"token": "x", "addresses": []}).status_code == 401
    too_many = ["a"] * (main.GEOCODE_BATCH_MAX + 1)
    r = client.post("/geocode-batch", json={"token": mint(), "addresses": too_many})
    assert r.status_code == 422


def test_geocode_batch_logs_counts_only(monkeypatch, capsys):
    monkeypatch.setattr(main, "resolve_point", lambda a, p: (1.0, 2.0, "uug"))
    client.post("/geocode-batch", json={"token": mint(), "addresses": ["Poznań, Sekretna 7"]})
    out = capsys.readouterr().out
    assert "coop_geocode_batch" in out
    assert "Sekretna" not in out
