import { describe, expect, it } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
import PizZip from "pizzip";
import { OPERAT_SECTION_TEMPLATES } from "../src/domain/operat-sections";

/**
 * F-12 (template leg): the committed production template must be scrubbed —
 * no PII from the source operat (PESEL, owner names, KW number), no
 * Kościelna-specific literals (they would leak into every generated operat),
 * no r² claim (the engine does not compute r²), and every placeholder from
 * the contract present. The .docx is a ZIP (binary to git grep), so F-9's
 * repo scan can NOT see inside it — this test is the enforcement.
 */
const TEMPLATE = path.join(process.cwd(), "templates", "operat-szablon.docx");

/**
 * Pin on the committed template's bytes (Slice 3, Task 10 — team-lead
 * condition): update this pin in the SAME commit as any template change, so
 * every edit to the binary is a deliberate, reviewed event rather than a
 * silent drift. Final wave B7: Table 1's Obręb/Odległość [m] column widths
 * swapped (`scripts/patch-template-table1.mts`) — content-only change, no
 * placeholder/text delta. Slice 3d: Table 1 back to the reference operat's layout
 * (`Data transakcji | Miasto | Ulica | Pow. uż. | Cena transakcyjna`) via
 * `scripts/patch-template-table1-ulica.mts` — {obreb}/{odleglosc} out of the loop,
 * {miasto}/{ulica} back in. Slice 3e: each photo loop collapsed from three paragraphs
 * to one (`scripts/patch-template-foto-2-kolumny.mts`) so the inline images wrap two
 * to a row — same placeholders, different paragraph structure. T-12 (S4): the
 * property-right switches — {przedmiot_m}/{przedmiot_d}, {#prawo_wlasnosc}/
 * {#prawo_spoldzielcze} alternatives and fences, {#ma_kw}/{#kw_brak},
 * {#ma_piwnice}, {podstawa_prawa} — generated by build_template.py stage 9d and
 * the three patch scripts re-applied on top (pipeline: generator, then patches).
 *
 * Paczka 1 (b1-template): etap 10c (czcionka stylów bazowych, M-6), 9e (§7 z
 * faktów), 9f (fraza o obciążeniu), 9g (autor i biuro z profilu), 9h (§15 i
 * Załącznik nr 1), 14 (§8.2 w kolejności wzorca) oraz 5e (§12.2 z danych lokali).
 * Cały pipeline uruchamia jedno polecenie: `pnpm --filter web template:build`.
 *
 * TP.6 (zrzuty z Worda): pasek kontaktowy okładki podniesiony do 88 pt bez
 * pustych akapitów odstępu (blok biura był ucinany) i §4 z łańcuchem keepNext
 * plus zwartą interlinią bloku adresowego.
 *
 * UWAGA o tym pinie (zmierzone 15.09): pipeline jest odtwarzalny co do
 * ZAWARTOŚCI, ale nie bajtowo — post-processy zipa zapisują wpisy bieżącym
 * czasem, więc SHA pliku zmienia się przy każdym przebiegu, nawet gdy
 * rozpakowane części są identyczne co do bajtu. Ten pin pilnuje więc, że
 * binarka w repo jest tą PRZEJRZANĄ, a nie że da się ją odtworzyć bajtowo;
 * odtwarzalność sprawdza się porównaniem rozpakowanych części.
 *
 * Głuszyna PR-2 (ADR-021): slot tabeli działów księgi gruntu po jej protokole
 * (`tabela_dzialow("ksiega_gruntu_wiersze")`), zdania ścieżki bez treści pod
 * `{^ma_tresc_gruntu}`.
 *
 * ADR-024: zdanie o ograniczonym zakresie między protokołem a tabelą księgi
 * gruntu, `{#zakres_ograniczony_gruntu}`. Generator z wiki a23642e (gałąź
 * PR #98, decyzja koordynatora 26.09); rozpakowany `word/document.xml` różni
 * się od poprzedniej binarki wyłącznie trzema wstawionymi akapitami.
 */
const TEMPLATE_SHA256 = "6dbdd2e3e28012bdb87b34b103c5f6507f24710fdd95c9c0cfd1c9af6654aac9";

function templateXml(): string {
  const zip = new PizZip(fs.readFileSync(TEMPLATE));
  return Object.keys(zip.files)
    .filter((f) => /^word\/(document|header\d*|footer\d*)\.xml$/.test(f))
    .map((f) => zip.files[f].asText())
    .join("\n");
}

/**
 * Visible text only — strips XML tags so placeholder checks match what
 * docxtemplater parses. NBSP (U+00A0, used as the thousands separator in the
 * source KCS tables) is normalized to a normal space so FORBIDDEN_LITERALS can
 * be written with ordinary spaces.
 */
function templateText(): string {
  return templateXml()
    .replace(/<[^>]+>/g, "")
    .replace(/ /g, " ");
}

const FORBIDDEN_LITERALS = [
  "Kościeln", // any case form of the source street/property
  "Rajewsk", // source clients' surname
  "mieszalnego", // source heading typo (should read "mieszkalnego") — regression-proof
  "7163/468337", // source building share
  "26.03.2026",
  "01.04.2026",
  "korelacji", // the r² methodology sentence must be gone
  // Task 2: KCS values now parameterized (Tabela 2/3/4 + §11 sample prose).
  // Written with normal spaces; templateText() normalizes NBSP→space.
  "12 061,94", // Tabela 2 cena minimalna -> {cena_min}
  "14 852,90", // Tabela 2 cena maksymalna -> {cena_max}
  "13 123,60", // Tabela 2 / Tabela 4 cena średnia -> {cena_sr}
  "14 580,32", // Tabela 4 wartość na 1 m2 -> {cena_1m2}
  "1 044 388,32", // Tabela 4 wartość rynkowa (dokładna) -> {wr_dokladna}
  "1 044 400,00", // wartość rynkowa po zaokrągleniu -> {wr}
  // Task 2 fix: sample transaction figures baked into §11/§13 prose — source
  // DATA (would render as false content in every other operat), not boilerplate.
  "675 000", // §11 general-market total price min
  "740 000", // §11 sample total price min
  "1 040 000", // §11 total price max (appears in both paragraphs)
  "844 421", // §11 general-market average total
  "874 333", // §11 sample average total
  "18 169", // §13 offer-price range max
  // Task 7: source-operat plan symbol must never be baked into the template.
  "4MW/U",
  // Task 9 (D10): sample KW/akt values must arrive via {udzial_kw} /
  // {pow_uzytkowa_kw}, never as literals baked into the 8.2 examination block.
  "14651/29359", // sample udział we współwłasności
  "146,5100", // sample powierzchnia użytkowa
  // Task 8 (Slice 7): §12.1 rating-scale definitions are parameterized — the
  // source operat's hardcoded scale texts must never ship in the template.
  "poniżej 65 m2",
  "4 piętro i powyżej",
  "prawo do wyłącznego korzystania z miejsca postojowego",
  // Task 9 (Slice 7 follow-up): hardcoded Kościelna feature lists / count must never ship.
  "dodatkowe oraz lokalizację szczegółową",
  "dodatkowe oraz lokalizacja szczegółowa",
  "za pomocą 5 atrybutów",
  // Slice "proza operatu" (T8): the §11 market-analysis criteria and the sample's
  // own figures were the source operat's, and the descriptive sections carried
  // "will be completed after the inspection" stubs. Both classes are now written
  // by the model into {proza_*}; neither may survive in the shipped template.
  "61,35", // sample area band (min) — §11
  "76,41", // sample area band (max) — §11
  "po 2000 r.", // construction-year selection criterion — §11
  "od 50 m2 do 90 m2", // area selection criterion — §11
  "poniżej 60 m2", // rejection criterion — §11
  "2 lata wstecz", // time-window selection criterion — §11
  // Descriptive stubs (§1 wyciąg, §8.1, §8.3, §8.4). NOTE the "po oględzinach"
  // suffix: `{^mapy}Dokumentacja kartograficzna zostanie uzupełniona.{/mapy}` is
  // an honest no-map variant, not a stub, and must keep rendering.
  "zostanie uzupełniony po oględzinach",
  "zostanie uzupełniona po oględzinach",
  // §11 correlation claims — the engine computes no such relationship (same
  // class as the r² sentence dropped in Slice 4). BOTH directions listed: the
  // generator deletes the two paragraphs under one assertion, and this list is
  // what keeps either of them from coming back ("mieszalnego" precedent).
  "odwrotnie proporcjonalna",
  "wprost proporcjonalna",
  // The application never looks at asking prices. Listed WITHOUT the
  // inflectional ending on purpose: the first version spelled the genitive
  // ("analizy rynku ofertowego") from §13, and the nominative went on shipping
  // in §7's list of sources — an independent review found it. Polish
  // declension is a hole in any guard that spells a whole phrase out.
  "rynku ofertowego",
  // §7 credited the location map to the city's own GIS while the caption the
  // generator inserts under the map says Geoportal — a contradiction a reader
  // catches by comparing two pages of the same operat.
  "System Informacji Przestrzennej",
  // The remaining paragraphs the prose stage deletes. A review restored five
  // of them in a mutant template and this list caught exactly one; the .docx
  // is binary to `git grep`, so what is not listed here is not guarded at all.
  "Cechy analizowanego rynku", // §11 selection-criteria block
  "W okresie monitorowania rynku", // §11 monitoring paragraph
  "W toku analizy odrzucono", // §11 rejected-transactions paragraph
  "odbywa się komunikacją miejską", // §8.1 — the source flat's own transit fact
  "mieści się w zbiorze", // §13 justification paragraph
  // Paczka 1 (TP.1) — trzy zdania, które szablon wypowiadał o KAŻDEJ wycenie,
  // prawdziwe tylko o operacie źródłowym:
  "Pełna treść odpisu KW", // D-21 — dowód, którego czytelnik operatu nie zobaczy
  "właściwy sąd rejonowy", // D-03/D-07 — §2 twierdziło o księdze gruntu bez numeru
  "umowa ustanowienia odrębnej własności lokalu i sprzedaży", // D-12 — akt INNEJ nieruchomości
  // Slice 3 (Task 10) forbade {miasto}/{ulica} here, because back then they were filled
  // from the SUBJECT's address (the bug Łukasz reported: every row said "Heweliusza 3").
  // Slice 3d brings both back — fed from the transaction's own record in the GEOPOZ
  // export — so the guard moved to where the danger actually is: the house number, which
  // must never reach the document (render test in f12-document-sections).
];

const REQUIRED_PLACEHOLDERS = [
  "{adres}",
  "{powierzchnia}",
  "{cel}",
  "{nr_kw}",
  "{klient}",
  "{data_ogledzin}",
  "{data_sporzadzenia}",
  "{wr}",
  "{wr_slownie}",
  "{wr_dokladna}",
  "{cena_min}",
  "{cena_max}",
  "{cena_sr}",
  "{polozenie_sr}",
  "{vmin}",
  "{vmax}",
  "{suma_ui}",
  "{cena_1m2}",
  "{#transakcje}",
  "{/transakcje}",
  "{#cechy}",
  "{/cechy}",
  "{#opis_przedmiot}",
  "{/opis_przedmiot}",
  // Paczka 1 (TP.4): §12.2 opisuje KAŻDY lokal o cenie skrajnej (remis, D-53)
  // jego własnymi danymi (D-52) i nazywa ulicę zamiast „analizowanego obszaru
  // rynku" (D-51). Płaskie `opis_cmin`/`opis_cmax` niosły tylko pierwszy lokal.
  "{#lokale_cmin}",
  "{/lokale_cmin}",
  "{#lokale_cmax}",
  "{/lokale_cmax}",
  "{#lokalizacja}",
  "{/lokalizacja}",
  "{lokalizacja}",
  "{nazwa} – {opis},",
  // Ui śr kolumny SUMA w Tabeli 3 — dotąd literał „1,000" z operatu źródłowego.
  "{suma_ui_sr}",
  "{#kredyt}",
  "{/kredyt}",
  // Task 7: EGiB facts block (8.2) + MPZP variants (9). Slice 3 (Task 10)
  // reuses the tag name "obreb" a second time, INSIDE {#transakcje}, for
  // each comparable's own obręb label. Slice 3d removed the loop's {obreb}/{odleglosc}
  // (those columns live in step 3 now), so the §8.2 one must SURVIVE ALONE — that is
  // exactly what this entry guards; Table 1's own columns are asserted at the bottom.
  "{obreb}",
  "{miasto}",
  "{ulica}",
  "{arkusz}",
  "{nr_dzialki}",
  "{pow_dzialki}",
  "{uzytek}",
  "{budynek_rodzaj}",
  "{kondygnacje}",
  "{rok_budowy}",
  // M-2 (D-05/D-06): the Wyciąg (s. 3) and §2 print ONE composed sentence, so
  // both slots carry the same tag — the count is asserted below, because two
  // places naming the subject differently is the defect this fix removes.
  "{oznaczenie_geodezyjne}",
  "{#ma_ewidencja}",
  "{^ma_ewidencja}",
  // M-1 (D-01): slot na zdjęcie nieruchomości na okładce — jedyne miejsce
  // fotograficzne, które generator zostawił bez tagu.
  "{%foto_okladka}",
  "{#ma_foto_okladka}",
  // M-10: §9 and §7's source bullet branch on the SAME three flags — the two
  // must never name different documents. `prz_brak_mpzp` is the union of the
  // two no-MPZP branches; `ma_przeznaczenie` gates the whole source sentence.
  "{#prz_mpzp}",
  "{/prz_mpzp}",
  "{#prz_plan_ogolny}",
  "{/prz_plan_ogolny}",
  "{#prz_studium}",
  "{/prz_studium}",
  "{#prz_brak_mpzp}",
  "{/prz_brak_mpzp}",
  "{#ma_przeznaczenie}",
  "{/ma_przeznaczenie}",
  "{#ma_publikator}",
  "{/ma_publikator}",
  "{prz_nazwa}",
  "{prz_uchwala}",
  "{prz_data}",
  "{prz_symbol}",
  "{prz_publikator}",
  // Task 9: 8.2 KW examination block — scalars, section pairs, loops.
  "{udzial_kw}",
  "{pow_uzytkowa_kw}",
  "{#pow_kw_present}",
  "{/pow_kw_present}",
  "{kw_zrodlo}",
  "{kw_lokalu}",
  "{kw_gruntu}",
  "{kw_sad}",
  "{kw_wydzial}",
  "{kw_data_dok}",
  "{#kw_badanie}",
  "{/kw_badanie}",
  "{#kw_standard}",
  "{/kw_standard}",
  "{#kw_deweloperski}",
  "{/kw_deweloperski}",
  // Paczka 1 (TP.2): §8.2 w kolejności operatu wzorcowego — protokół badania
  // każdej księgi, potem jej działy (transkrypcja jako tabela albo zdania
  // ścieżki ręcznej), na końcu akapit o obciążeniu. Dawna para
  // `dzialN_brak`/`dzialN_wpisy` wyszła razem z wierszami, które ją czytały.
  "{#ma_protokol_ksiegi_lokalu}",
  "{/ma_protokol_ksiegi_lokalu}",
  "{protokol_ksiegi_lokalu}",
  "{#ma_protokol_ksiegi_gruntu}",
  "{/ma_protokol_ksiegi_gruntu}",
  "{protokol_ksiegi_gruntu}",
  "{#ma_tresc_lokalu}",
  "{^ma_tresc_lokalu}",
  "{/ma_tresc_lokalu}",
  "{#ksiega_lokalu_wiersze}",
  "{/ksiega_lokalu_wiersze}",
  // Głuszyna PR-2 (ADR-021 reg. 6): księga gruntu ma tę samą tabelę działów co
  // lokal — slot po protokole gruntu, z odwrotną gałęzią dla zdań ścieżki bez treści.
  "{#ma_tresc_gruntu}",
  "{^ma_tresc_gruntu}",
  "{/ma_tresc_gruntu}",
  "{#ksiega_gruntu_wiersze}",
  "{/ksiega_gruntu_wiersze}",
  // ADR-024: zdanie o zakresie przed tabelą gruntu.
  "{#zakres_ograniczony_gruntu}",
  "{/zakres_ograniczony_gruntu}",
  "{kol1}",
  "{kol2}",
  "{kol3}",
  "{dzial3_opis}",
  "{dzial4_opis}",
  "{dzial3_opis_gruntu}",
  "{dzial4_opis_gruntu}",
  "{nr_lokalu_kw}",
  "{#obciazenie_bez_uwzglednienia}",
  "{/obciazenie_bez_uwzglednienia}",
  "{#obciazenie_z_uwzglednieniem}",
  "{/obciazenie_z_uwzglednieniem}",
  "{obciazenie_podstawa}",
  // Paczka 1 (TP.1): §2's land-register sentence and §7's two source bullets
  // stopped being literals of the source operat. Each prints only under its own
  // fact — an examined ground book (with its court, when the book carries one)
  // and a deed read from dział II. `{#kw_stub_odpis}` left with the sentence it
  // gated ("Pełna treść odpisu KW…", D-21), and so did the model flag.
  "{#ma_ksiege_gruntu}",
  "{/ma_ksiege_gruntu}",
  "{#sad_ksiegi_gruntu}",
  "{^sad_ksiegi_gruntu}",
  "{/sad_ksiegi_gruntu}",
  "{nr_ksiegi_gruntu}",
  "{sad_ksiegi_gruntu}",
  "{#ma_akt}",
  "{/ma_akt}",
  "{akt_opis}",
  // T-12 (S4): property-right switches. The sentences themselves live in
  // domain/property-right.ts — the template carries only these tags.
  "{przedmiot_m}",
  "{przedmiot_d}",
  "{podstawa_prawa}",
  "{#prawo_wlasnosc}",
  "{/prawo_wlasnosc}",
  "{#prawo_spoldzielcze}",
  "{/prawo_spoldzielcze}",
  "{#ma_kw}",
  "{/ma_kw}",
  "{#kw_brak}",
  "{/kw_brak}",
  "{klauzula_brak_kw}",
  "{#ma_piwnice}",
  "{/ma_piwnice}",
  "{klauzula_piwnicy}",
  // Task 8 (Slice 7): §12.1 rating-scale loop.
  "{#skala_ocen}",
  "{/skala_ocen}",
  "{#poziomy}",
  "{/poziomy}",
  "{cecha}",
  "{poziom}",
  "{def}",
  // Task 9: truthful feature-list intro + honest-silence wrap.
  "{cechy_lista}",
  "{cechy_lista_wg_wag}",
  "{liczba_atrybutow_fraza}",
  "{#ma_skale}",
  "{/ma_skale}",
  // Slice 9: §8.1 map block (built by build_template.py map stage)
  "{#mapy}",
  "{%mapa_ewidencyjna}",
  "{%mapa_orto}",
  "{mapy_data}",
  "{^mapy}",
  // Slice 10 (Task 6, FR-2): §8.1/§8.3 inspection photo blocks — budynek,
  // otoczenie, wnetrza loops each wrapping the shared {%img} image tag, plus
  // the free-text inspection-notes block (build_template.py stage 13).
  "{#ma_foto_budynek}",
  "{/ma_foto_budynek}",
  "{#foto_budynek}",
  "{/foto_budynek}",
  "{#ma_foto_otoczenie}",
  "{/ma_foto_otoczenie}",
  "{#foto_otoczenie}",
  "{/foto_otoczenie}",
  "{#ma_foto_wnetrza}",
  "{/ma_foto_wnetrza}",
  "{#foto_wnetrza}",
  "{/foto_wnetrza}",
  "{%img}",
  "{#ma_uwagi_ogledzin}",
  "{/ma_uwagi_ogledzin}",
  "{uwagi_ogledzin}",
  // Slice "proza operatu" (T8, ADR-014/FR-6): the six model-written sections.
  // `otoczenie` and `zagospodarowanie` are trailing clauses of a paragraph that
  // keeps its own address sentence, so an empty value already renders as
  // silence; the four that OWN their paragraph carry a {#ma_proza_*} wrap so a
  // draft without prose shows no heading over emptiness.
  // M-11 (D-36): cztery samodzielne sloty prozy to PĘTLE po akapitach, więc
  // gołego tagu już nie mają — dokument dostaje osobne `<w:p>` zamiast jednego
  // bloku rozciąganego przez justowanie. `{proza_opis_lokalu}` zostaje, bo
  // niesie je jeszcze komórka Wyciągu, gdzie kontynuuje literał.
  "{#proza_analiza_rynku_ak}",
  "{#proza_opis_lokalu_ak}",
  "{#proza_standard_ak}",
  "{#proza_uzasadnienie_ak}",
  "{tekst}",
  "{proza_otoczenie}",
  "{proza_zagospodarowanie}",
  "{proza_opis_lokalu}",
  "{#ma_proza_analiza_rynku}",
  "{/ma_proza_analiza_rynku}",
  "{#ma_proza_opis_lokalu}",
  "{/ma_proza_opis_lokalu}",
  "{#ma_proza_standard}",
  "{/ma_proza_standard}",
  "{#ma_proza_uzasadnienie}",
  "{/ma_proza_uzasadnienie}",
];

describe("F-12: template integrity (operat-szablon.docx)", () => {
  it("template bytes are the reviewed ones (update the pin in the same commit as the template)", () => {
    expect(createHash("sha256").update(fs.readFileSync(TEMPLATE)).digest("hex")).toBe(
      TEMPLATE_SHA256,
    );
  });

  it("contains no PESEL-like or KW-shaped strings anywhere in the XML", () => {
    const xml = templateXml();
    expect(xml).not.toMatch(/\d{11}/);
    expect(xml).not.toMatch(/[A-Z]{2}\d[A-Z]\s*\/\s*\d{8}\s*\/\s*\d/);
  });

  it("contains no source-operat literals", () => {
    const text = templateText();
    for (const lit of FORBIDDEN_LITERALS) {
      expect(text, `forbidden literal "${lit}" still in template`).not.toContain(lit);
    }
  });

  it("contains every contract placeholder", () => {
    const text = templateText();
    for (const ph of REQUIRED_PLACEHOLDERS) {
      expect(text, `missing placeholder ${ph}`).toContain(ph);
    }
  });

  it("contains the {%podpis} signature tag exactly once (Slice 8)", () => {
    const text = templateText();
    expect(text.match(/\{%podpis\}/g)).toHaveLength(1);
  });

  // ADR-006 (AC-8): the honest weights-methodology sentence must be present —
  // the r² claim was removed in Slice 4; this is its truthful replacement.
  it("contains the honest weights-methodology sentence (ADR-006 short variant)", () => {
    expect(templateText()).toContain(
      "Wagi cech rynkowych przyjęto na podstawie analizy rynku lokalnego",
    );
  });

  it("has at least 19 canonical section headings, all present in the template", () => {
    expect(OPERAT_SECTION_TEMPLATES.length).toBeGreaterThanOrEqual(19);
    const text = templateText();
    for (const heading of OPERAT_SECTION_TEMPLATES) {
      expect(text, `missing section heading "${heading}"`).toContain(heading);
    }
  });

  // Task 8 (Slice 7) review fix F3: the §12.1 rating-scale loop must stay a
  // MULTI-paragraph loop — {#poziomy}/{poziom} – {def}/{/poziomy}/{/skala_ocen}
  // each on their OWN <w:p> — regardless of punctuation. This is the durable
  // structural guard for the anti-run-on failure class (an INLINE loop would
  // glue consecutive levels into one paragraph with no separator, the exact
  // bug f12-document-sections.test.ts's `/powyżejprzeciętna|pośredniegorsza/`
  // regex catches downstream, by content); this test catches it upstream, by
  // shape, so it fires even if a future edit removes/changes the wording.
  it("keeps each §12.1 skala_ocen loop tag in its own paragraph (anti run-on structural guard)", () => {
    // docxtemplater tags can be split across multiple <w:t> runs in raw XML
    // (see templateText()'s NBSP-normalize precedent) — strip tags WITHIN each
    // paragraph chunk before searching, mirroring that normalization idiom.
    const paragraphs = templateXml()
      .split("</w:p>")
      .map((chunk) => chunk.replace(/<[^>]+>/g, ""));
    const loopTags = ["{#poziomy}", "{poziom} – {def}", "{/poziomy}", "{/skala_ocen}"];
    const indices = loopTags.map((tag) => paragraphs.findIndex((p) => p.includes(tag)));
    loopTags.forEach((tag, i) => {
      expect(indices[i], `tag ${tag} not found in any single paragraph`).toBeGreaterThanOrEqual(0);
    });
    expect(new Set(indices).size, "each tag must live in a distinct paragraph").toBe(
      loopTags.length,
    );
    expect(indices, "tags must appear in ascending document order").toEqual(
      [...indices].sort((a, b) => a - b),
    );
  });

  it("carries no source-operat metadata in docProps/core.xml", () => {
    // docxtemplater preserves non-document parts verbatim, so whatever sits
    // in the template's file properties ships into EVERY generated operat.
    const zip = new PizZip(fs.readFileSync(TEMPLATE));
    const core = zip.files["docProps/core.xml"].asText();
    expect(core, "source author leaks into generated documents").not.toContain("Audytor");
    expect(core, "source last-modified-by leaks into generated documents").not.toContain("Ksobiak");
    expect(core, "source lastPrinted timestamp must be scrubbed").not.toContain("cp:lastPrinted");
  });
});

describe("F-12: Table 1 follows the reference operat's layout (Slice 3d)", () => {
  it("has the reference headers, in order, and no obręb/odległość column left", () => {
    // Aneta's operat: `Data transakcji | Miasto | Ulica | Pow. uż. [m2] | Cena
    // transakcyjna [zł/m2]` (operat-koscielna s. 1000-1009). The row loop must match.
    const text = templateText();
    const table1 = text.slice(text.indexOf("Tabela 1"), text.indexOf("Tabela 2"));

    expect(table1).toContain("Data transakcjiMiastoUlicaPow. uż. [m2]Cena transakcyjna [zł/m2]");
    expect(table1).toContain("{#transakcje}{data_msc}{miasto}{ulica}{pow}{cena_jedn}{/transakcje}");
    expect(table1).not.toContain("{obreb}");
    expect(table1).not.toContain("{odleglosc}");
  });

  it("keeps the subject's own {obreb} in §8.2 — a different field, untouched by 3d", () => {
    const text = templateText();
    const afterTable1 = text.slice(text.indexOf("Tabela 2"));
    expect(
      afterTable1.includes("{obreb}") ||
        text.slice(0, text.indexOf("Tabela 1")).includes("{obreb}"),
    ).toBe(true);
  });
});

/**
 * M-2 (D-05/D-06). Do 16.09 Wyciąg i §2 drukowały stałe „wg wypisu z ewidencji
 * gruntów i budynków", choć §8.2 tego samego operatu wyliczał te dane — generator
 * zamaskował zdanie operatu źródłowego i nikt nie wstawił tagów z powrotem.
 * Placeholder ZOSTAJE jako gałąź odwrotna, więc nie da się go zakazać literałem;
 * broni tu liczność tagów, a treści broni render w `f12-document-sections`.
 */
/**
 * D-30 jako KLASA, nie pojedynczy akapit. Word rozciąga do pełnej szerokości
 * każdą linię akapitu justowanego, która kończy się miękkim łamaniem — także
 * tę, która normalnie byłaby ostatnią i poszłaby do lewej. Tak wyglądało §11
 * („Cechy   analizowanego   rynku:") i tak nadal wyglądało §12.1 po naprawie
 * M-11: „jednostkowe   ceny   transakcyjne   nieruchomości   podobnych."
 * Zmierzone na operacie wydanym na stagingu 16.09: dziewięć takich akapitów
 * w §1, §2, §12.1, §13 i §14.
 */
describe("F-12: twarde łamania tylko tam, gdzie mają sens", () => {
  it("żaden akapit justowany nie niesie <w:br/>", () => {
    const xml = templateXml();
    const winne = (xml.match(/<w:p[ >][\s\S]*?<\/w:p>/g) ?? []).filter(
      (p) => p.includes('<w:jc w:val="both"/>') && /<w:br\s*\/>/.test(p),
    );
    expect(winne).toEqual([]);
  });

  it("zostawia łamania w akapitach NIEjustowanych — tam niosą treść", () => {
    // Dwuwierszowy nagłówek Tabeli 1 („Pow. uż. [m2]") jest wyśrodkowany, więc
    // reguła go omija bez wyjątku wpisanego z ręki. Tym samym mechanizmem
    // ocalony jest blok biura na okładce: {biuro} dostaje swoje łamania
    // dopiero przy renderze i też nie jest justowany.
    const xml = templateXml();
    const zLamaniem = (xml.match(/<w:p[ >][\s\S]*?<\/w:p>/g) ?? []).filter((p) =>
      /<w:br\s*\/>/.test(p),
    );
    expect(zLamaniem.length).toBeGreaterThan(0);
  });
});

/**
 * I-05 as a PLACEMENT map, not a presence check. Both tags have existed in the
 * template all along — `{proza_standard}` was simply under the wrong heading,
 * so a test asking "is the tag there?" passed on the broken 14.09 operat. What
 * Aneta reported (M-7, D-26) is WHERE the text prints, so that is what is
 * pinned: for each §8.3 heading, the exact prose loops between it and the next.
 */
describe("F-12: każda sekcja opisowa §8.3 pod swoim nagłówkiem (M-7, D-26, I-05)", () => {
  /** Paragraph texts in document order — `<w:t>` runs only, never `<w:tab>`. */
  function paragraphTexts(): string[] {
    return (templateXml().match(/<w:p[ >][\s\S]*?<\/w:p>/g) ?? []).map((p) =>
      (p.match(/<w:t(?:\s[^>]*)?>[^<]*<\/w:t>/g) ?? [])
        .map((run) => run.replace(/<[^>]+>/g, ""))
        .join("")
        .trim(),
    );
  }

  /** The prose loops opened between `heading` and the next paragraph starting with `until`. */
  function proseLoopsUnder(heading: string, until: string): string[] {
    const texts = paragraphTexts();
    const from = texts.indexOf(heading);
    expect(from, `heading "${heading}" not found`).toBeGreaterThanOrEqual(0);
    const to = texts.findIndex((t, i) => i > from && t.startsWith(until));
    expect(to, `no "${until}" after "${heading}"`).toBeGreaterThan(from);
    return texts.slice(from + 1, to).flatMap((t) => t.match(/\{#proza_[a-z_]+_ak\}/g) ?? []);
  }

  it("pod „Opis budynku” stoi wyłącznie opis budynku — nie wykończenie lokalu", () => {
    expect(proseLoopsUnder("Opis budynku", "Opis lokalu mieszkalnego")).toEqual([
      "{#proza_opis_budynku_ak}",
    ]);
  });

  it("pod „Opis lokalu mieszkalnego” stoją układ i wykończenie, w tej kolejności", () => {
    expect(proseLoopsUnder("Opis lokalu mieszkalnego", "8.4.")).toEqual([
      "{#proza_opis_lokalu_ak}",
      "{#proza_standard_ak}",
    ]);
  });

  it("galeria wnętrz idzie po CAŁYM opisie lokalu, a klauzula piwnicy na końcu §8.3", () => {
    // Stage 9d and stage 13 insert right after their anchor, so the later one
    // lands closest. Anchored on the layout block they put the photos between
    // the layout and the finish — the order is the thing to pin.
    //
    // Searched from the "Opis budynku" heading on: `{#ma_piwnice}` also opens a
    // block in the §1 Wyciąg, and a document-wide `indexOf` would compare §8.3
    // against the summary table — the same trap stage 13 once guarded against
    // with a `rindex`.
    const texts = paragraphTexts();
    const from = texts.indexOf("Opis budynku");
    const at = (tag: string) => texts.indexOf(tag, from);
    expect(at("{/ma_proza_opis_lokalu}")).toBeGreaterThan(from);
    expect(at("{/ma_proza_opis_lokalu}")).toBeLessThan(at("{#ma_proza_standard}"));
    expect(at("{/ma_proza_standard}")).toBeLessThan(at("{#ma_foto_wnetrza}"));
    expect(at("{/ma_foto_wnetrza}")).toBeLessThan(at("{#ma_piwnice}"));
  });
});

describe("F-12: identyfikacja geodezyjna w Wyciągu i §2 (M-2)", () => {
  it("prints the same composed sentence in both places, each behind the same fence", () => {
    const text = templateText();
    const count = (s: string) => text.split(s).length - 1;
    expect(count("{oznaczenie_geodezyjne}")).toBe(2);
    expect(count("{#ma_ewidencja}")).toBe(2);
    expect(count("{^ma_ewidencja}")).toBe(2);
    expect(count("{/ma_ewidencja}")).toBe(4);
    // Placeholder tylko w gałęzi odwrotnej — nigdy poza ogrodzeniem.
    expect(count("wg wypisu z ewidencji gruntów i budynków")).toBe(2);
  });

  it("keeps both slots OUTSIDE {#prawo_wlasnosc} — spółdzielczy operat też ma identyfikację", () => {
    const text = templateText();
    // Każdy fragment między otwarciem a zamknięciem ogrodzenia własności.
    const inside = text
      .split("{#prawo_wlasnosc}")
      .slice(1)
      .map((part) => part.split("{/prawo_wlasnosc}")[0]);
    for (const region of inside) expect(region).not.toContain("{oznaczenie_geodezyjne}");
  });
});

/**
 * Dwa defekty, których nie widać w TEKŚCIE dokumentu — złapane dopiero zrzutem
 * z Worda (TP.6, 15.09). Oba dotyczą akapitów, które paczka 1 sama wstawiła,
 * więc asercje siedzą na SZABLONIE, nie na renderze: w renderze tekst jest
 * kompletny w obu przypadkach, a błędem jest to, czego Word z nim robi.
 */
describe("F-12: geometria miejsc dołożonych w paczce 1 (TP.6)", () => {
  it("pasek kontaktowy okładki mieści blok biura zamiast go uciąć", () => {
    const xml = templateXml();
    // Kształt był wymiarowany pod jedną linijkę „tel. … e-mail … www”: przy
    // 83,85 pt (cy=1064895) i dwóch pustych akapitach odstępu trzyliniowy blok
    // urywał się w połowie trzeciej linii, bez śladu w XML.
    expect(xml, "stara wysokość paska kontaktowego").not.toContain('cy="1064895"');
    expect(xml.match(/cy="1117600"/g) ?? [], "wysokość w obu wymiarach DrawingML").toHaveLength(2);
    expect(xml, "kopia VML paska").toContain("height:88.0pt");
    // Samo autofit nie wystarcza (Word ufa zapisanej wysokości przy otwarciu),
    // ale zostaje, żeby ręczna edycja u rzeczoznawcy rosła z treścią.
    expect(xml, "autofit DrawingML").toContain("<a:spAutoFit/>");
    expect(xml, "autofit VML").toContain("mso-fit-shape-to-text:t");
    expect(xml, "stare noAutofit").not.toContain("<a:noAutofit/>");

    // W obu kopiach pola (I-18) zostają dokładnie dwa akapity: logo i {biuro}.
    const boxes = [...xml.matchAll(/<w:txbxContent>([\s\S]*?)<\/w:txbxContent>/g)];
    expect(boxes, "dwie kopie pola tekstowego").toHaveLength(2);
    for (const [, box] of boxes) {
      expect(box.match(/<w:p[ >]/g) ?? [], "akapity w pasku kontaktowym").toHaveLength(2);
      expect(box, "logo zostaje").toContain("<w:drawing>");
      expect(box, "blok biura zostaje").toContain("{biuro}");
    }
  });

  it("§4: blok biura trzyma się zdania i nagłówka, i ma zwartą interlinię", () => {
    const xml = templateXml();
    // Od POCZĄTKU akapitu nagłówka (jego `pPr` z keepNext stoi przed tekstem),
    // nie od samego napisu — pierwsze wystąpienie obu tytułów to spis treści.
    const naglowek = xml.indexOf(
      "Podstawa formalna wyceny",
      xml.indexOf("Podstawa formalna wyceny") + 1,
    );
    const sec4 = xml.slice(
      xml.lastIndexOf("<w:p ", naglowek),
      xml.indexOf("Podstawy prawne", xml.indexOf("Podstawy prawne") + 1),
    );
    expect(sec4, "zakres §4 znaleziony").toContain("{biuro}");
    // Łańcuch keepNext: nagłówek → pusty akapit odstępu → zdanie o zleceniu.
    // Bez ogniwa pośredniego Word zostawiał nagłówek z pustką na poprzedniej
    // stronie, a zdanie z adresem przenosił na następną.
    expect(sec4.match(/<w:keepNext[ /]/g) ?? [], "ogniwa keepNext w §4").toHaveLength(3);
    // Adres to nie proza: bez własnego `spacing` dziedziczy interlinię 276
    // i pięciolinijkowy blok rozłazi się na pół strony.
    const blok = sec4.slice(sec4.lastIndexOf("<w:p ", sec4.indexOf("{biuro}")));
    expect(blok).toContain('w:line="240"');
    expect(blok).toContain('w:after="0"');
  });
});
