import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { nextCookies } from "better-auth/next-js";
import { db } from "../db/client";
import * as schema from "../db/schema";

/**
 * Better Auth server instance (ADR-013).
 *
 * Owns the `user`/`session`/`account`/`verification` tables via the Drizzle
 * adapter (see `../db/auth-schema.ts`, generated by `@better-auth/cli`).
 * `role` is a custom field on `user` — the only extension this app needs.
 *
 * Minimal (walking skeleton, YAGNI): email/password only, no OAuth, no email
 * verification, no password reset.
 *
 * Closed system (ADR-013, ~5 trusted internal employees): `disableSignUp:
 * true` closes the public `POST /api/auth/sign-up/email` endpoint. Per
 * Better Auth's `sign-up/email` route source, this same flag also gates
 * server-side `auth.api.signUpEmail(...)` calls (both paths run through the
 * same endpoint handler) — so `scripts/seed.ts` creates demo users via the
 * internal adapter (`auth.$context`) instead, using Better Auth's own
 * password hasher directly. See seed.ts for details.
 */
export const auth = betterAuth({
  database: drizzleAdapter(db, {
    provider: "pg",
    schema,
  }),
  emailAndPassword: {
    enabled: true,
    disableSignUp: true,
  },
  user: {
    additionalFields: {
      role: {
        type: ["admin", "appraiser"],
        required: true,
        input: false,
        // Least privilege: any future sign-up (none exists yet — no
        // registration page, YAGNI) defaults to the non-admin role. The seed
        // script promotes the admin demo user explicitly after creation.
        defaultValue: "appraiser",
      },
    },
  },
  // Auto-sets Set-Cookie headers when calling auth.api.* from Server Actions.
  plugins: [nextCookies()],
});
